FORMAT: 1A
HOST: http://flask-boilerplate.com/
# Sample API
A Flask API Boilerplate
## Main Collection [/healthz]
### Healthz connection [GET]
+ Response 200 (application/json)
            {
                 "Status": "Some body call for the exterminator?",
            }